# Generated by Django 5.1.7 on 2025-04-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FloodPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('water_level', models.FloatField()),
                ('river_discharge', models.FloatField()),
                ('rainfall', models.FloatField()),
                ('elevation', models.FloatField()),
                ('humidity', models.FloatField()),
                ('temperature', models.FloatField()),
                ('population_density', models.FloatField()),
                ('predicted_risk', models.CharField(max_length=50)),
            ],
        ),
    ]
